#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Template Marketplace Feature

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================
echo ""
echo "Checking prerequisites..."

# Check Python
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Python 3 not found. Please install Python 3.8+${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Python found${NC}"

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js 16+${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js found${NC}"

# Check Docker (optional, for PostgreSQL/Redis)
if command -v docker &> /dev/null; then
    echo -e "${GREEN}✓ Docker found${NC}"
else
    echo -e "${YELLOW}⚠ Docker not found (optional for local DB)${NC}"
fi

# ============================================
# START INFRASTRUCTURE (Optional)
# ============================================
echo ""
echo "Starting infrastructure services..."

if [ -f "docker-compose.yml" ]; then
    echo "Starting PostgreSQL and Redis via docker-compose..."
    docker-compose up -d
    sleep 3
    echo -e "${GREEN}✓ Database and cache services started${NC}"
else
    echo -e "${YELLOW}⚠ docker-compose.yml not found, skipping infrastructure startup${NC}"
fi

# ============================================
# START BACKEND
# ============================================
echo ""
echo "Starting backend service..."

cd "$(dirname "$0")/../../.." # Go to project root

# Check if virtual environment exists
if [ ! -d ".venv" ] && [ ! -d "venv" ]; then
    echo -e "${YELLOW}Virtual environment not found, creating one...${NC}"
    python3 -m venv .venv
fi

# Activate virtual environment
if [ -d ".venv" ]; then
    source .venv/bin/activate
elif [ -d "venv" ]; then
    source venv/bin/activate
fi

# Install backend dependencies if needed
if [ -f "requirements.txt" ]; then
    echo "Installing Python dependencies..."
    pip install -q -r requirements.txt
fi

# Start Flask backend in background
echo "Starting Flask backend..."
export FLASK_APP=app.py
export FLASK_ENV=development
export DATABASE_URL=${DATABASE_URL:-postgresql://dumont:dumont123@localhost:5432/dumont_cloud}
export REDIS_URL=${REDIS_URL:-redis://localhost:6379/0}
export APP_PORT=${APP_PORT:-8000}
export DEBUG=${DEBUG:-true}

python app.py &
BACKEND_PID=$!
echo "Backend started (PID: $BACKEND_PID)"

# Wait for backend to be ready
wait_for_service 8000 "Backend API"

# ============================================
# START FRONTEND
# ============================================
echo ""
echo "Starting frontend service..."

cd web

# Install frontend dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
fi

# Start Vite dev server in background
echo "Starting Vite dev server..."
npm run dev &
FRONTEND_PID=$!
echo "Frontend started (PID: $FRONTEND_PID)"

# Note: Vite typically runs on port 5173, not 8000
# Adjust based on actual vite.config.js settings

# ============================================
# SUMMARY
# ============================================
echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  Frontend:     http://localhost:5173 (or check Vite output above)"
echo ""
echo "API Endpoints:"
echo "  GET  /api/templates              - List all templates"
echo "  GET  /api/templates/:slug        - Get template details"
echo "  POST /api/templates/:slug/deploy - Deploy template"
echo ""
echo "Environment Variables:"
echo "  DATABASE_URL: $DATABASE_URL"
echo "  REDIS_URL:    $REDIS_URL"
echo "  APP_PORT:     $APP_PORT"
echo ""
echo "Process IDs:"
echo "  Backend:  $BACKEND_PID"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo "  docker-compose down  # If using Docker"
echo ""
echo "========================================"
