#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Enhanced Machine Reliability Scoring

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Enhanced Machine Reliability Scoring"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# VERIFY ENVIRONMENT
# ============================================
echo ""
echo "Verifying environment variables..."

if [ -z "$DATABASE_URL" ]; then
    echo -e "${YELLOW}Warning: DATABASE_URL not set, using default${NC}"
    export DATABASE_URL="postgresql://dumont:dumont123@localhost:5432/dumont_cloud"
fi

if [ -z "$REDIS_URL" ]; then
    echo -e "${YELLOW}Warning: REDIS_URL not set, using default${NC}"
    export REDIS_URL="redis://localhost:6379/0"
fi

if [ -z "$VAST_API_KEY" ]; then
    echo -e "${RED}Warning: VAST_API_KEY not set${NC}"
fi

# ============================================
# START INFRASTRUCTURE
# ============================================
echo ""
echo "Starting infrastructure services (PostgreSQL, Redis)..."
docker-compose up -d postgres redis 2>/dev/null || echo -e "${YELLOW}Docker compose not available or already running${NC}"

# Wait for database
wait_for_service 5432 "PostgreSQL"

# Wait for Redis
wait_for_service 6379 "Redis"

# ============================================
# START BACKEND
# ============================================
echo ""
echo "Starting Backend (FastAPI)..."
cd src || { echo -e "${RED}src/ directory not found${NC}"; exit 1; }

# Run database migrations
echo "Running database migrations..."
alembic upgrade head || echo -e "${YELLOW}Migrations failed or not configured${NC}"

# Start backend in background
python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload &
BACKEND_PID=$!
cd ..

wait_for_service 8000 "Backend API"

# ============================================
# START FRONTEND
# ============================================
echo ""
echo "Starting Frontend (React/Vite)..."
cd web || { echo -e "${RED}web/ directory not found${NC}"; exit 1; }

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing frontend dependencies..."
    npm install
fi

# Start frontend in background
npm run dev &
FRONTEND_PID=$!
cd ..

# Wait for Vite dev server (usually on 5173)
sleep 3
wait_for_service 5173 "Frontend" || echo -e "${YELLOW}Frontend may be on different port${NC}"

# ============================================
# SUMMARY
# ============================================
echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  Frontend UI:  http://localhost:5173"
echo "  PostgreSQL:   localhost:5432"
echo "  Redis:        localhost:6379"
echo ""
echo "Backend PID: $BACKEND_PID"
echo "Frontend PID: $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo "  docker-compose down"
echo ""
echo "Ready for implementation!"
echo "========================================"
