#!/bin/bash

# GPU Reservation System - Development Environment Setup
# Generated by Planner Agent

set -e

echo "========================================"
echo "GPU Reservation System - Starting Dev Environment"
echo "========================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "⏳ Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}❌ $name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}✅ $name ready on port $port${NC}"
}

# ============================================
# DATABASE SETUP
# ============================================

echo ""
echo "📦 Database Setup"
echo "----------------------------------------"

# Check if PostgreSQL is running
if ! nc -z localhost 5432 2>/dev/null; then
    echo -e "${YELLOW}⚠️  PostgreSQL not detected on port 5432${NC}"
    echo "Please start PostgreSQL:"
    echo "  docker-compose up -d postgres"
    echo "  OR: brew services start postgresql@14"
    exit 1
fi

echo -e "${GREEN}✅ PostgreSQL running${NC}"

# Run database migrations
echo "Running database migrations..."
cd /Users/marcos/OrbStack/dumontcloud/home/marcos/projects/dumont-cloud
python -c "from src.config.database import init_db; init_db(); print('Database initialized')" || echo "Database already initialized"

# ============================================
# BACKEND SERVICE (FastAPI)
# ============================================

echo ""
echo "🐍 Starting Backend (FastAPI)"
echo "----------------------------------------"

cd /Users/marcos/OrbStack/dumontcloud/home/marcos/projects/dumont-cloud

# Kill existing processes on port 8000
if lsof -ti:8000 &>/dev/null; then
    echo "Killing existing process on port 8000..."
    kill -9 $(lsof -ti:8000) 2>/dev/null || true
    sleep 2
fi

# Start backend
python -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8000 &
BACKEND_PID=$!

wait_for_service 8000 "Backend API"

# ============================================
# FRONTEND SERVICE (React + Vite)
# ============================================

echo ""
echo "⚛️  Starting Frontend (React + Vite)"
echo "----------------------------------------"

cd /Users/marcos/OrbStack/dumontcloud/home/marcos/projects/dumont-cloud/web

# Kill existing processes on port 5173
if lsof -ti:5173 &>/dev/null; then
    echo "Killing existing process on port 5173..."
    kill -9 $(lsof -ti:5173) 2>/dev/null || true
    sleep 2
fi

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing frontend dependencies..."
    npm install
fi

# Start frontend dev server
npm run dev &
FRONTEND_PID=$!

wait_for_service 5173 "Frontend Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "✅ Environment Ready!"
echo "========================================"
echo ""
echo "Services Running:"
echo "  🗄️  PostgreSQL:    postgresql://dumont:dumont123@localhost:5432/dumont_cloud"
echo "  🔌 Backend API:    http://localhost:8000"
echo "  📝 API Docs:       http://localhost:8000/docs"
echo "  🌐 Frontend:       http://localhost:5173"
echo "  📱 Web App:        http://localhost:8000/app"
echo ""
echo "PIDs:"
echo "  Backend:  $BACKEND_PID"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo "Next Steps:"
echo "  1. Open http://localhost:5173 in your browser"
echo "  2. Navigate to /app/reservations to see the calendar"
echo "  3. Start implementing subtasks from implementation_plan.json"
echo ""
echo "========================================"
