// Demo machines data with rich details for demo mode
export const DEMO_MACHINES = [
  {
    id: 12345678,
    gpu_name: 'RTX 4090',
    actual_status: 'running',
    status: 'running',
    gpu_ram: 24576,
    cpu_cores: 16,
    cpu_ram: 64,
    disk_space: 500,
    dph_total: 0.45,
    total_dph: 0.46,
    public_ipaddr: '203.0.113.45',
    ssh_host: 'ssh4.vast.ai',
    ssh_port: 22345,
    start_date: new Date(Date.now() - 3600000 * 5).toISOString(),
    label: 'dev-workspace-01',
    gpu_util: 45.2,
    gpu_temp: 62,
    ports: {
      '22/tcp': [{ HostPort: '22345' }],
      '8080/tcp': [{ HostPort: '8080' }]
    },
    provider: 'vast.ai',
    cpu_standby: {
      enabled: true,
      provider: 'gcp',
      name: 'standby-dev-us',
      zone: 'us-central1-a',
      ip: '35.192.45.123',
      machine_type: 'e2-medium',
      status: 'running',
      dph_total: 0.01,
      sync_enabled: true,
      sync_count: 234,
      state: 'ready'
    }
  },
  {
    id: 23456789,
    gpu_name: 'A100 80GB',
    actual_status: 'running',
    status: 'running',
    gpu_ram: 81920,
    cpu_cores: 32,
    cpu_ram: 128,
    disk_space: 1000,
    dph_total: 2.10,
    total_dph: 2.11,
    public_ipaddr: '198.51.100.78',
    ssh_host: 'ssh7.vast.ai',
    ssh_port: 22789,
    start_date: new Date(Date.now() - 3600000 * 12).toISOString(),
    label: 'ml-training-large',
    gpu_util: 92.5,
    gpu_temp: 71,
    ports: {
      '22/tcp': [{ HostPort: '22789' }],
      '8080/tcp': [{ HostPort: '8080' }],
      '6006/tcp': [{ HostPort: '6006' }]
    },
    provider: 'vast.ai',
    cpu_standby: {
      enabled: true,
      provider: 'gcp',
      name: 'standby-ml-eu',
      zone: 'europe-west1-b',
      ip: '35.204.123.45',
      machine_type: 'e2-medium',
      status: 'running',
      dph_total: 0.01,
      sync_enabled: true,
      sync_count: 567,
      state: 'syncing'
    }
  },
  {
    id: 34567890,
    gpu_name: 'RTX 3090',
    actual_status: 'stopped',
    status: 'stopped',
    gpu_ram: 24576,
    cpu_cores: 12,
    cpu_ram: 48,
    disk_space: 250,
    dph_total: 0.35,
    total_dph: 0.35,
    ssh_host: 'ssh2.vast.ai',
    ssh_port: 22123,
    label: 'stable-diffusion-dev',
    provider: 'vast.ai',
    cpu_standby: null
  },
  {
    id: 45678901,
    gpu_name: 'RTX 4080',
    actual_status: 'stopped',
    status: 'stopped',
    gpu_ram: 16384,
    cpu_cores: 8,
    cpu_ram: 32,
    disk_space: 200,
    dph_total: 0.28,
    total_dph: 0.28,
    ssh_host: 'ssh5.vast.ai',
    ssh_port: 22456,
    label: 'inference-api',
    provider: 'vast.ai',
    cpu_standby: null
  },
  {
    id: 56789012,
    gpu_name: 'H100 80GB',
    actual_status: 'running',
    status: 'running',
    gpu_ram: 81920,
    cpu_cores: 64,
    cpu_ram: 256,
    disk_space: 2000,
    dph_total: 3.50,
    total_dph: 3.51,
    public_ipaddr: '192.0.2.100',
    ssh_host: 'ssh9.vast.ai',
    ssh_port: 22999,
    start_date: new Date(Date.now() - 3600000 * 2).toISOString(),
    label: 'llm-finetuning',
    gpu_util: 78.3,
    gpu_temp: 68,
    ports: {
      '22/tcp': [{ HostPort: '22999' }],
      '8080/tcp': [{ HostPort: '8080' }]
    },
    provider: 'vast.ai',
    cpu_standby: {
      enabled: true,
      provider: 'gcp',
      name: 'standby-llm-us',
      zone: 'us-east1-b',
      ip: '35.231.89.123',
      machine_type: 'e2-standard-4',
      status: 'running',
      dph_total: 0.02,
      sync_enabled: true,
      sync_count: 89,
      state: 'ready'
    }
  }
]

// Demo deployed models for Models page
export const DEMO_MODELS = [
  {
    id: 'model-001',
    name: 'Llama 3.2 3B Instruct',
    model_id: 'meta-llama/Llama-3.2-3B-Instruct',
    model_type: 'llm',
    status: 'running',
    runtime: 'vLLM',
    gpu_name: 'RTX 4090',
    num_gpus: 1,
    dph_total: 0.45,
    endpoint_url: 'https://llm-001.dumont.cloud/v1',
    access_type: 'private',
    api_key: 'dm-sk-xxxx-xxxx-xxxx-xxxx-demo001',
    progress: 100,
    status_message: 'Running',
    port: 8000,
  },
  {
    id: 'model-002',
    name: 'Whisper Large V3',
    model_id: 'openai/whisper-large-v3',
    model_type: 'speech',
    status: 'running',
    runtime: 'faster-whisper',
    gpu_name: 'RTX 3090',
    num_gpus: 1,
    dph_total: 0.35,
    endpoint_url: 'https://whisper-001.dumont.cloud/transcribe',
    access_type: 'public',
    progress: 100,
    status_message: 'Running',
    port: 8001,
  },
  {
    id: 'model-003',
    name: 'FLUX.1 Schnell',
    model_id: 'black-forest-labs/FLUX.1-schnell',
    model_type: 'image',
    status: 'deploying',
    runtime: 'diffusers',
    gpu_name: 'RTX 4090',
    num_gpus: 1,
    dph_total: 0.45,
    progress: 67,
    status_message: 'Downloading model weights...',
    port: 8002,
  },
]

// Demo templates for model deployment wizard
export const DEMO_TEMPLATES = [
  {
    type: 'llm',
    name: 'LLM (Chat/Completion)',
    description: 'Deploy modelos de linguagem para chat e text completion',
    runtime: 'vLLM',
    gpu_memory_required: 8,
    default_port: 8000,
    popular_models: [
      { id: 'meta-llama/Llama-3.2-3B-Instruct', name: 'Llama 3.2 3B Instruct', size: '3B' },
      { id: 'Qwen/Qwen2.5-7B-Instruct', name: 'Qwen 2.5 7B Instruct', size: '7B' },
      { id: 'mistralai/Mistral-7B-Instruct-v0.3', name: 'Mistral 7B Instruct', size: '7B' },
      { id: 'google/gemma-2-9b-it', name: 'Gemma 2 9B IT', size: '9B' },
    ],
  },
  {
    type: 'speech',
    name: 'Speech (Transcription)',
    description: 'Transcreva áudio para texto com alta precisão',
    runtime: 'faster-whisper',
    gpu_memory_required: 4,
    default_port: 8001,
    popular_models: [
      { id: 'openai/whisper-large-v3', name: 'Whisper Large V3', size: '1.5B' },
      { id: 'openai/whisper-medium', name: 'Whisper Medium', size: '769M' },
      { id: 'openai/whisper-small', name: 'Whisper Small', size: '244M' },
    ],
  },
  {
    type: 'image',
    name: 'Image (Generation)',
    description: 'Gere imagens a partir de texto (text-to-image)',
    runtime: 'diffusers',
    gpu_memory_required: 12,
    default_port: 8002,
    popular_models: [
      { id: 'black-forest-labs/FLUX.1-schnell', name: 'FLUX.1 Schnell', size: '12B' },
      { id: 'stabilityai/stable-diffusion-xl-base-1.0', name: 'SDXL Base', size: '3.5B' },
      { id: 'runwayml/stable-diffusion-v1-5', name: 'SD 1.5', size: '1B' },
    ],
  },
  {
    type: 'embeddings',
    name: 'Embeddings (Vectors)',
    description: 'Gere embeddings para busca semântica e RAG',
    runtime: 'sentence-transformers',
    gpu_memory_required: 2,
    default_port: 8003,
    popular_models: [
      { id: 'BAAI/bge-large-en-v1.5', name: 'BGE Large EN', size: '335M' },
      { id: 'intfloat/e5-large-v2', name: 'E5 Large V2', size: '335M' },
      { id: 'sentence-transformers/all-MiniLM-L6-v2', name: 'MiniLM L6', size: '22M' },
    ],
  },
]
