#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Internationalization (English + Spanish)

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Feature: i18n - English + Spanish"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Web Frontend (React + Vite)
echo ""
echo -e "${YELLOW}Starting Web Frontend...${NC}"
cd web
npm install
npm run dev &
WEB_PID=$!
cd ..

wait_for_service 8000 "Web Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Web Frontend: http://localhost:8000"
echo ""
echo "Process IDs:"
echo "  Web: $WEB_PID"
echo ""
echo "To stop services:"
echo "  kill $WEB_PID"
echo ""
echo "Next Steps:"
echo "  1. Open browser at http://localhost:8000"
echo "  2. Start implementing subtasks from implementation_plan.json"
echo "  3. Use 'source auto-claude/.venv/bin/activate && python auto-claude/run.py --spec 015 --parallel 3' for automated implementation"
echo ""
echo "========================================"
