#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Webhook Integration System

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Feature: Webhook Integration System"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

# Check Python dependencies
if ! python -c "import httpx" 2>/dev/null; then
    echo -e "${YELLOW}httpx not found, installing...${NC}"
    pip install httpx==0.28.1
fi

if ! python -c "import tenacity" 2>/dev/null; then
    echo -e "${YELLOW}tenacity not found, installing...${NC}"
    pip install tenacity==9.1.2
fi

if ! python -c "import sqlalchemy" 2>/dev/null; then
    echo -e "${YELLOW}sqlalchemy not found, installing...${NC}"
    pip install sqlalchemy==2.0.40
fi

echo -e "${GREEN}Dependencies OK${NC}"

# ============================================
# DATABASE SETUP
# ============================================

echo ""
echo "Setting up database..."

# Check PostgreSQL connection
if ! pg_isready -h localhost -p 5432 -U dumont 2>/dev/null; then
    echo -e "${RED}PostgreSQL not running on localhost:5432${NC}"
    echo "Please start PostgreSQL and try again"
    exit 1
fi

echo -e "${GREEN}PostgreSQL connection OK${NC}"

# Run database migrations (if needed)
echo "Running database migrations..."
python -c "from src.config.database import init_db; init_db(); print('Database initialized')"

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# Backend API
echo "Starting Backend API (FastAPI)..."
cd /Users/marcos/OrbStack/dumontcloud/home/marcos/projects/dumont-cloud
uvicorn src.main:app --reload --host 0.0.0.0 --port 8000 &
BACKEND_PID=$!

# Wait for backend to be ready
wait_for_service 8000 "Backend API"

# Frontend Dev Server
echo "Starting Frontend Dev Server (Vite)..."
cd /Users/marcos/OrbStack/dumontcloud/home/marcos/projects/dumont-cloud/web
npm run dev &
FRONTEND_PID=$!

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  API Docs:     http://localhost:8000/docs"
echo "  Frontend:     http://localhost:8000"
echo ""
echo "Database:"
echo "  PostgreSQL:   localhost:5432/dumont_cloud"
echo ""
echo "PIDs:"
echo "  Backend:  $BACKEND_PID"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo "========================================"
