#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for NPS and Feedback Collection System

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

# Check PostgreSQL
if ! command -v psql &> /dev/null; then
    echo -e "${YELLOW}Warning: psql not found. PostgreSQL may not be installed.${NC}"
else
    echo -e "${GREEN}PostgreSQL client found${NC}"
fi

# Check Python
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: python3 not found${NC}"
    exit 1
else
    echo -e "${GREEN}Python3 found${NC}"
fi

# Check Node/npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm not found${NC}"
    exit 1
else
    echo -e "${GREEN}npm found${NC}"
fi

# ============================================
# CHECK DATABASE
# ============================================

echo ""
echo "Checking database connection..."

DB_USER="${DB_USER:-dumont}"
DB_PASSWORD="${DB_PASSWORD:-dumont123}"
DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"
DB_NAME="${DB_NAME:-dumont_cloud}"

export PGPASSWORD="$DB_PASSWORD"
if psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "SELECT 1;" &> /dev/null; then
    echo -e "${GREEN}Database connection successful${NC}"
else
    echo -e "${RED}Error: Cannot connect to database${NC}"
    echo "Database URL: postgresql://$DB_USER:****@$DB_HOST:$DB_PORT/$DB_NAME"
    echo "Make sure PostgreSQL is running and credentials are correct"
    exit 1
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "========================================"
echo "Starting Services"
echo "========================================"

# Backend (FastAPI)
echo ""
echo "Starting Backend (FastAPI)..."
cd "$PROJECT_ROOT" || exit 1
python -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload &
BACKEND_PID=$!
echo "Backend PID: $BACKEND_PID"

# Wait for backend
wait_for_service 8000 "Backend"

# Frontend (Vite)
echo ""
echo "Starting Frontend (Vite)..."
cd "$PROJECT_ROOT/web" || exit 1
npm run dev &
FRONTEND_PID=$!
echo "Frontend PID: $FRONTEND_PID"

# Note: Frontend proxies through backend on port 8000
# Vite dev server runs on 5173 but users access via http://localhost:8000

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000/api/v1"
echo "  Frontend:     http://localhost:8000"
echo "  API Docs:     http://localhost:8000/docs"
echo ""
echo "Database:"
echo "  PostgreSQL:   postgresql://$DB_USER:****@$DB_HOST:$DB_PORT/$DB_NAME"
echo ""
echo "Process IDs:"
echo "  Backend:      $BACKEND_PID"
echo "  Frontend:     $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo "========================================"
