#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 016: Multi-Currency Pricing System

set -e

echo "========================================"
echo "Multi-Currency Pricing - Dev Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PRE-CHECKS
# ============================================

echo ""
echo "Checking environment..."

# Check Python
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Python 3 not found. Please install Python 3.8+${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Python 3 found${NC}"

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js 16+${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js found${NC}"

# Check PostgreSQL
if ! command -v psql &> /dev/null; then
    echo -e "${YELLOW}⚠ PostgreSQL CLI not found. Make sure PostgreSQL is accessible.${NC}"
fi

# Check Redis
if ! command -v redis-cli &> /dev/null; then
    echo -e "${YELLOW}⚠ Redis CLI not found. Make sure Redis is accessible.${NC}"
fi

# Check .env file
if [ ! -f .env ]; then
    echo -e "${RED}.env file not found. Please create it from .env.example${NC}"
    exit 1
fi
echo -e "${GREEN}✓ .env file found${NC}"

# Check for required environment variables
if ! grep -q "EXCHANGE_RATE_API_KEY" .env; then
    echo -e "${YELLOW}⚠ EXCHANGE_RATE_API_KEY not found in .env. Please add it.${NC}"
    echo "  EXCHANGE_RATE_API_KEY=your_api_key_here"
fi

if ! grep -q "EXCHANGE_RATE_API_URL" .env; then
    echo -e "${YELLOW}⚠ EXCHANGE_RATE_API_URL not found in .env. Please add it.${NC}"
    echo "  EXCHANGE_RATE_API_URL=https://api.exchangerate-api.io/v4/latest/USD"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

# Backend dependencies
echo "Installing backend Python dependencies..."
if [ -f requirements.txt ]; then
    pip install babel apscheduler httpx || echo -e "${YELLOW}⚠ Some backend dependencies may not have installed${NC}"
    echo -e "${GREEN}✓ Backend dependencies installed${NC}"
else
    echo -e "${YELLOW}⚠ requirements.txt not found${NC}"
fi

# Frontend dependencies
echo "Installing frontend JavaScript dependencies..."
if [ -f web/package.json ]; then
    cd web
    npm install dinero.js @dinero.js/currencies || echo -e "${YELLOW}⚠ Some frontend dependencies may not have installed${NC}"
    cd ..
    echo -e "${GREEN}✓ Frontend dependencies installed${NC}"
else
    echo -e "${YELLOW}⚠ web/package.json not found${NC}"
fi

# ============================================
# DATABASE SETUP
# ============================================

echo ""
echo "Setting up database..."

# Source environment variables
set -a
source .env
set +a

# Check if PostgreSQL is running
if psql -U "$DB_USER" -h "$DB_HOST" -p "$DB_PORT" -d "$DB_NAME" -c "SELECT 1" &> /dev/null; then
    echo -e "${GREEN}✓ PostgreSQL connection successful${NC}"

    # Run migrations (if migration system exists)
    if [ -f src/migrations/add_currency_tables.py ]; then
        echo "Running currency migrations..."
        python src/migrations/add_currency_tables.py || echo -e "${YELLOW}⚠ Migration may have failed${NC}"
    fi
else
    echo -e "${YELLOW}⚠ PostgreSQL connection failed. Database may not be accessible.${NC}"
    echo "  Connection: postgresql://$DB_USER@$DB_HOST:$DB_PORT/$DB_NAME"
fi

# ============================================
# REDIS SETUP
# ============================================

echo ""
echo "Checking Redis..."

if redis-cli ping &> /dev/null; then
    echo -e "${GREEN}✓ Redis connection successful${NC}"
else
    echo -e "${YELLOW}⚠ Redis connection failed. Cache may not be available.${NC}"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "========================================"
echo "Starting Services"
echo "========================================"

# Start backend (FastAPI with scheduler)
echo "Starting backend (port 8000)..."
cd src
python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload &
BACKEND_PID=$!
cd ..

sleep 3
wait_for_service 8000 "Backend API"

# Start frontend (Vite dev server)
echo "Starting frontend..."
cd web
npm run dev &
FRONTEND_PID=$!
cd ..

sleep 3
# Frontend port may vary - Vite typically uses 5173 or 8000
# Check both
if nc -z localhost 5173 2>/dev/null; then
    echo -e "${GREEN}Frontend ready on port 5173${NC}"
elif nc -z localhost 8000 2>/dev/null; then
    echo -e "${GREEN}Frontend ready on port 8000${NC}"
else
    echo -e "${YELLOW}⚠ Frontend may not have started. Check logs.${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  Frontend:     http://localhost:5173 (or check Vite output)"
echo "  PostgreSQL:   localhost:${DB_PORT} (database: ${DB_NAME})"
echo "  Redis:        localhost:6379"
echo ""
echo "API Documentation:"
echo "  http://localhost:8000/docs (Swagger UI)"
echo ""
echo "Process IDs:"
echo "  Backend: $BACKEND_PID"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo "Next Steps:"
echo "  1. Verify scheduler is running (check backend logs)"
echo "  2. Check exchange rates were fetched"
echo "  3. Test currency selector in frontend"
echo "  4. Verify price conversion"
echo ""
echo "========================================"
