#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Task: Verificar e Corrigir Migração GPU-para-CPU

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Project directory
PROJECT_DIR="$(dirname "$0")/../../.."
cd "$PROJECT_DIR"

echo -e "${BLUE}📁 Project directory: $(pwd)${NC}"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${YELLOW}⏳ Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}❌ $name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}✅ $name ready on port $port${NC}"
}

# ============================================
# STEP 1: Install Test Dependencies
# ============================================

echo ""
echo -e "${BLUE}📦 Step 1: Installing test dependencies...${NC}"

if [ -d "tests" ]; then
    cd tests
    if [ -f "package.json" ]; then
        echo "Installing npm dependencies in tests/..."
        npm install 2>/dev/null || echo -e "${YELLOW}⚠️ npm install had warnings (may be normal)${NC}"

        echo "Installing Playwright browsers..."
        npx playwright install chromium 2>/dev/null || echo -e "${YELLOW}⚠️ Playwright browser install had warnings${NC}"
    fi
    cd ..
    echo -e "${GREEN}✅ Test dependencies installed${NC}"
else
    echo -e "${RED}❌ tests/ directory not found${NC}"
fi

# ============================================
# STEP 2: Install Web Frontend Dependencies
# ============================================

echo ""
echo -e "${BLUE}📦 Step 2: Installing web frontend dependencies...${NC}"

if [ -d "web" ]; then
    cd web
    if [ -f "package.json" ]; then
        echo "Installing npm dependencies in web/..."
        npm install 2>/dev/null || echo -e "${YELLOW}⚠️ npm install had warnings (may be normal)${NC}"
    fi
    cd ..
    echo -e "${GREEN}✅ Web frontend dependencies installed${NC}"
else
    echo -e "${RED}❌ web/ directory not found${NC}"
fi

# ============================================
# STEP 3: Start Frontend Dev Server (background)
# ============================================

echo ""
echo -e "${BLUE}🚀 Step 3: Starting frontend development server...${NC}"

if [ -d "web" ]; then
    cd web
    npm run dev &
    FRONTEND_PID=$!
    cd ..

    echo "Frontend starting with PID: $FRONTEND_PID"

    # Wait for frontend to be ready
    wait_for_service 5173 "Frontend (Vite)"
else
    echo -e "${RED}❌ Cannot start frontend - web/ directory not found${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:5173"
echo "  App:       http://localhost:5173/app"
echo ""
echo "Test Commands:"
echo "  cd tests && USE_DEMO_MODE=true npx playwright test e2e-journeys/cpu-standby-failover.spec.js"
echo "  cd tests && USE_DEMO_MODE=true npx playwright test e2e-journeys/failover-complete-journeys.spec.js"
echo "  cd tests && npx playwright show-report"
echo ""
echo "To stop the frontend server:"
echo "  kill $FRONTEND_PID"
echo ""
